name: workshop-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx=0.10
  - pyvista>=0.45.0
  - ipyparallel
  - mpi4py
  - scipy
  - vtk
  - pygraphviz
  - jupyter-book
  - jupytext
  - trame-client
  - trame-vtk
  - trame-server
  - trame-vuetify
  - trame
  - ipywidgets
  - sphinx>=6.0.0
  - python-gmsh
variables:
  PYVISTA_OFF_SCREEN: false
  PYVISTA_JUPYTER_BACKEND: "trame"
  LIBGL_ALWAYS_SOFTWARE: 1
